name: Deploy README with Theme to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install Bundler
        run: gem install bundler --user-install

      - name: Configure gem path
        run: echo 'export GEM_HOME=$HOME/.gem' >> $GITHUB_ENV

      - name: Add Bundler to PATH
        run: echo 'export PATH=$HOME/.gem/bin:$PATH' >> $GITHUB_ENV

      - name: Source environment variables
        run: source $GITHUB_ENV

      - name: Verify Bundler installation
        run: |
          echo "GEM_HOME: $GEM_HOME"
          echo "PATH: $PATH"
          which bundle
          bundle --version

      - name: Build with Jekyll
        run: |
          echo "remote theme: UiCore/finflow" > _config.yml
          echo "---\nlayout: default\n---\n{% include_relative README.md %}" > index.md
          bundle install --path "$HOME/.gem"
          bundle exec jekyll build -d ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
