name: Deploy README with Theme to GitHub Pages

on:
  push:
    branches: ["main"]  # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

permissions:
  contents: read  # Grant read permission to contents
  pages: write  # Grant write permission to GitHub Pages
  id-token: write  # Grant write permission to id-token

concurrency:
  group: "pages"  # Group for concurrency control
  cancel-in-progress: false  # Do not cancel in-progress jobs

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Checkout the repository
      
      - name: Setup Pages
        uses: actions/configure-pages@v5  # Setup GitHub Pages
      
      - name: Install Bundler
        run: gem install bundler --user-install  # Install Bundler gem
      
      - name: Configure gem path
        run: echo 'export GEM_HOME=$HOME/.gem' >> $GITHUB_ENV  # Set GEM_HOME environment variable
      
      - name: Add Bundler to PATH
        run: echo 'export PATH=$HOME/.gem/bin:$PATH' >> $GITHUB_ENV  # Add Bundler to PATH
      
      - name: Verify Bundler installation  # Verify that Bundler is installed correctly
        run: |
          echo "GEM_HOME: $GEM_HOME"
          echo "PATH: $PATH"
          which bundle
          bundle --version
      
      - name: Build with Jekyll  # Build the site with Jekyll
        run: |
          echo "remote theme: UiCore/finflow" > _config.yml
          echo "---\nlayout: default\n---\n{% include_relative README.md %}" > index.md
          bundle install --path "$HOME/.gem"
          bundle exec jekyll build -d ./_site

      - name: Upload artifact  # Upload the generated site as an artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages  # Environment name for GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}  # URL of the deployed site
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    needs: build  # Run this job after the build job
    steps:
      - name: Deploy to GitHub Pages  # Deploy the site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
